version: '2.1'
services:
    redis:
        image: 'redis:5.0.5'
        # command: redis-server --requirepass redispass

    pg-0:
        image: bitnami/postgresql-repmgr:10
        restart: always
        ports:
            - 5432
        volumes:
            - pg_0_data:/bitnami/postgresql
        environment:
            - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
            - POSTGRESQL_USERNAME=airflow
            - POSTGRESQL_PASSWORD=airflow
            - POSTGRESQL_DATABASE=airflow
            - REPMGR_PASSWORD=repmgrpassword
            - REPMGR_PRIMARY_HOST=pg-0
            - REPMGR_PARTNER_NODES=pg-0
            - REPMGR_NODE_NAME=pg-0
            - REPMGR_NODE_NETWORK_NAME=pg-0
    postgres:
        image: bitnami/pgpool:4
        ports:
            - 5432:5432
        volumes:
            - ./pgpool/conf:/opt/bitnami/pgpool/conf
        environment:
            - PGPOOL_BACKEND_NODES=0:pg-0:5432
            - PGPOOL_SR_CHECK_USER=airflow
            - PGPOOL_SR_CHECK_PASSWORD=airflow
            - PGPOOL_ENABLE_LDAP=no
            - PGPOOL_POSTGRES_USERNAME=postgres
            - PGPOOL_POSTGRES_PASSWORD=adminpassword
            - PGPOOL_ADMIN_USERNAME=admin
            - PGPOOL_ADMIN_PASSWORD=adminpassword

    webserver:
        image: pbotapps.azurecr.io/airflow
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        volumes:
            - ./.output:/usr/local/airflow/tmp
            - ./config/airflow.cfg:/usr/local/airflow/airflow.cfg
            - ./dags:/usr/local/airflow/dags
            - ./logs:/usr/local/airflow/logs
        ports:
            - '8080:8080'
        command: webserver
        healthcheck:
            test:
                ['CMD-SHELL', '[ -f /usr/local/airflow/airflow-webserver.pid ]']
            interval: 30s
            timeout: 30s
            retries: 3
    scheduler:
        image: pbotapps.azurecr.io/airflow
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./.output:/usr/local/airflow/tmp
            - ./config/airflow.cfg:/usr/local/airflow/airflow.cfg
            - ./dags:/usr/local/airflow/dags
            - ./logs:/usr/local/airflow/logs
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        command: scheduler
    worker:
        image: pbotapps.azurecr.io/airflow
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./.output:/usr/local/airflow/tmp
            - ./config/airflow.cfg:/usr/local/airflow/airflow.cfg
            - ./dags:/usr/local/airflow/dags
            - ./logs:/usr/local/airflow/logs
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        command: worker
    flower:
        image: pbotapps.azurecr.io/airflow
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./.output:/usr/local/airflow/tmp
            - ./config/airflow.cfg:/usr/local/airflow/airflow.cfg
            - ./dags:/usr/local/airflow/dags
            - ./logs:/usr/local/airflow/logs
        ports:
            - '5555:5555'
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        command: flower
    sharedstreets:
        image: pbotapps.azurecr.io/sharedstreets-api
        restart: always
volumes:
    pg_0_data:
        driver: local
