version: 2

container_config: &container_config
  docker:
    - image: mcdonaldmike/docker-azure:stable
  working_directory: /usr/local/lib
cache_key: &cache_key
  docker_cache-{{ .Branch }}-{{ .Revision   }}
restore_cache: &restore_cache
  restore_cache:
    name: Restore cache
    key: *cache_key
generate_tag_name: &generate_tag_name
  run:
    name: Generate tag name
    command: |
      echo 'export TAG_NAME=$(echo "${CIRCLE_BRANCH////-}")' >> $BASH_ENV
      
jobs:
  build_image:
    <<: *container_config
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - *generate_tag_name
      - run:
          name: Build docker image
          command: |
            docker build -t $IMAGE_NAME:$TAG_NAME .
      - run:
          name: Test docker image
          command: |
            docker run $IMAGE_NAME:$TAG_NAME version | grep '1.10.2'
      - run:
          name: Save docker image
          command: |
            mkdir -p docker-cache
            echo "Saving $IMAGE_NAME:$TAG_NAME"
            docker save -o docker-cache/image.tar $IMAGE_NAME:$TAG_NAME
      - save_cache:
          key: *cache_key
          paths:
            - docker-cache

  deploy_image:
    <<: *container_config
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - *restore_cache
      - *generate_tag_name
      - run:
          name: Login to Azure
          command: |
            az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
      - run:
          name: Login to Azure Container Registry
          command: |
            az acr login --name $AZURE_CONTAINER_REGISTRY
      - run:
          name: Load docker image
          command: |
            docker load < docker-cache/image.tar
      - run:
          name: Push image to Azure Container Registry
          command: |
            docker push $IMAGE_NAME:$TAG_NAME
      - run:
          name: Tag as latest
          command: |
            docker tag $IMAGE_NAME:$TAG_NAME $IMAGE_NAME:latest
      - run:
          name: Push latest tag image to Azure Container Registry
          command: |
            docker push $IMAGE_NAME:latest

  update_aks:
    <<: *container_config
    steps:
      - *generate_tag_name
      - run:
          name: Login to Azure
          command: |
            az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
      - run:
          name: Login to Kubernetes cluster
          command: |
            az aks get-credentials --name $K8S_CLUSTER_NAME --resource-group $K8S_RESOURCE_GROUP
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_image
      - deploy_image:
          requires:
            - build_image
          filters:
            branches:
              only:
                - master
            tags:
              only: /[0-9]+(\.[0-9]+)*/
      - update_aks:
          requires:
            - deploy_image
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/


