apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-env
  labels:
    app: postgres
data:
  POSTGRES_DB: airflow
  POSTGRES_USER: airflowadmin
  POSTGRES_PASSWORD: admin123
  PGDATA: /var/lib/postgresql/data/pgdata