---
# Source: airflow/templates/deployments-flower.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: airflow-flower
    labels:
        app: airflow
        component: flower
spec:
    replicas: 1
    minReadySeconds: 10
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
    selector:
        matchLabels:
            app: airflow
            component: flower
    template:
        metadata:
            annotations:
                checksum/config-env: 09c0b816c26040730d0592ef304d387444071d0f91d78ca5c69b762ef70ac067
            labels:
                app: airflow
                component: flower

        spec:
            restartPolicy: Always
            containers:
                - name: airflow-flower
                  image: pudlapps.azurecr.io/airflow:1.10.7.3
                  imagePullPolicy: IfNotPresent
                  envFrom:
                      - configMapRef:
                            name: 'airflow-env'
                  env:
                      - name: FERNET_KEY
                        valueFrom:
                            secretKeyRef:
                                name: airflow-fernet
                                key: fernet-key
                      - name: POSTGRES_USER
                        value: airflowadmin
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: airflow-postgresql
                                key: postgres-password
                      - name: REDIS_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: airflow-redis
                                key: redis-password
                      - name: HASH_SALT
                        valueFrom:
                            secretKeyRef:
                                name: airflow-hash
                                key: salt
                      - name: SENDGRID_MAIL_FROM
                        valueFrom:
                            secretKeyRef:
                                name: airflow-sendgrid
                                key: from
                      - name: SENDGRID_API_KEY
                        valueFrom:
                            secretKeyRef:
                                name: airflow-sendgrid
                                key: api-key
                  ports:
                      - name: flower
                        containerPort: 5555
                        protocol: TCP
                  args: ['flower']
                  livenessProbe:
                      httpGet:
                          path: '//'
                          port: flower
                      initialDelaySeconds: 60
                      periodSeconds: 60
                      timeoutSeconds: 1
                      successThreshold: 1
                      failureThreshold: 5
                  resources: {}
