apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: airflow
    component: database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        component: database
    spec:
      restartPolicy: Always
      serviceAccountName: airflow
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-env
          env:          
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: postgres-password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/pgdata
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim