---
# Source: airflow/templates/poddisruptionbudget.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: airflow-pdb
  labels:
    app: airflow
    component: scheduler
spec:
  selector:
    matchLabels:
      app: airflow
      component: scheduler
  maxUnavailable: 1
