apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: airflow
    component: database
spec:
  type: ClusterIP
  selector:
    app: airflow
    component: database
  ports:
   - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432