---
# Source: airflow/templates/service-flower.yaml
apiVersion: v1
kind: Service
metadata:
  name: airflow-flower
  labels:
    app: airflow
    component: flower
  annotations:
spec:
  type: ClusterIP
  selector:
    app: airflow
    component: flower
  ports:
    - name: flower
      protocol: TCP
      port: 5555
      targetPort: 5555
