---
# Source: airflow/templates/service-web.yaml
apiVersion: v1
kind: Service
metadata:
  name: airflow-web
  labels:
    app: airflow
    component: web
  annotations:
spec:
  type: ClusterIP
  selector:
    app: airflow
    component: web
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
