apiVersion: v1
kind: Service
metadata:
  name: airflow-redis
  labels:
    app: airflow
    component: cache
spec:
  type: ClusterIP
  selector:
    app: airflow
    component: cache
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379