---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: azure-disk-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi