kind: PersistentVolume
apiVersion: v1
metadata:
  name: airflow-logs-pv-volume
  labels:
    type: local
    app: airflow
spec:
  storageClassName: azure-file
  capacity:
    storage: 1024Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/usr/local/airflow/logs"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-logs-pv-claim
  labels:
    app: airflow
spec:
  storageClassName: azure-file
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1024Gi
