kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azure-file-retain
provisioner: kubernetes.io/azure-file
reclaimPolicy: Retain
mountOptions:
  - dir_mode=0777
  - file_mode=0777
parameters:
  skuName: Standard_LRS
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azure-disk-retain
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
parameters:
  storageaccounttype: Premium_LRS
  kind: Managed